# ==============================================================================
# Custom FindWebView2.cmake - supports multiple NuGet package layouts
#
# JUCE's default only checks PackageManagement path. This also checks:
#   - .nuget/packages (NuGet CLI / dotnet - has version subfolder)
#   - _tools/packages (project-local nuget.exe install output)
# ==============================================================================

include(FindPackageHandleStandardArgs)

set(WebView2_root_dir "")
set(WebView2_include_dir "")
set(WebView2_library "")

if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "arm64")
    set(WebView2_arch arm64)
else()
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(WebView2_arch x64)
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
        set(WebView2_arch x86)
    endif()
endif()

# 1) JUCE_WEBVIEW2_PACKAGE_LOCATION or PackageManagement (original JUCE logic)
if(JUCE_WEBVIEW2_PACKAGE_LOCATION)
    set(initial_search_dir ${JUCE_WEBVIEW2_PACKAGE_LOCATION})
else()
    set(initial_search_dir "$ENV{USERPROFILE}/AppData/Local/PackageManagement/NuGet/Packages")
endif()

file(GLOB subdirs "${initial_search_dir}/*Microsoft.Web.WebView2*")
if(subdirs)
    list(GET subdirs 0 search_dir)
    find_path(WebView2_root_dir build/native/include/WebView2.h HINTS ${search_dir})
    if(WebView2_root_dir)
        set(WebView2_include_dir "${WebView2_root_dir}/build/native/include")
        set(WebView2_library "${WebView2_root_dir}/build/native/${WebView2_arch}/WebView2LoaderStatic.lib")
    endif()
endif()

# 2) .nuget/packages layout (microsoft.web.webview2/<version>/build/...)
if(NOT WebView2_root_dir AND EXISTS "$ENV{USERPROFILE}/.nuget/packages/microsoft.web.webview2")
    file(GLOB _wv2_versions "$ENV{USERPROFILE}/.nuget/packages/microsoft.web.webview2/*")
    foreach(_ver ${_wv2_versions})
        if(IS_DIRECTORY "${_ver}" AND EXISTS "${_ver}/build/native/include/WebView2.h")
            set(WebView2_root_dir "${_ver}")
            set(WebView2_include_dir "${_ver}/build/native/include")
            set(WebView2_library "${_ver}/build/native/${WebView2_arch}/WebView2LoaderStatic.lib")
            break()
        endif()
    endforeach()
    unset(_wv2_versions)
    unset(_ver)
endif()

# 3) Project-local _tools/packages (nuget.exe install -OutputDirectory)
if(NOT WebView2_root_dir)
    set(_proj_packages "${CMAKE_SOURCE_DIR}/_tools/packages")
    if(EXISTS "${_proj_packages}")
        file(GLOB _wv2_pkgs "${_proj_packages}/*Microsoft.Web.WebView2*" "${_proj_packages}/*icrosoft.web.webview2*")
        foreach(_pkg ${_wv2_pkgs})
            if(IS_DIRECTORY "${_pkg}")
                if(EXISTS "${_pkg}/build/native/include/WebView2.h")
                    set(WebView2_root_dir "${_pkg}")
                    set(WebView2_include_dir "${_pkg}/build/native/include")
                    set(WebView2_library "${_pkg}/build/native/${WebView2_arch}/WebView2LoaderStatic.lib")
                    break()
                endif()
                file(GLOB _vers "${_pkg}/*")
                foreach(_v ${_vers})
                    if(IS_DIRECTORY "${_v}" AND EXISTS "${_v}/build/native/include/WebView2.h")
                        set(WebView2_root_dir "${_v}")
                        set(WebView2_include_dir "${_v}/build/native/include")
                        set(WebView2_library "${_v}/build/native/${WebView2_arch}/WebView2LoaderStatic.lib")
                        break()
                    endif()
                endforeach()
                if(WebView2_root_dir)
                    break()
                endif()
            endif()
        endforeach()
        unset(_wv2_pkgs)
        unset(_vers)
        unset(_v)
    endif()
    unset(_proj_packages)
    unset(_pkg)
endif()

find_package_handle_standard_args(WebView2 DEFAULT_MSG WebView2_include_dir WebView2_library)

if(WebView2_FOUND)
    set(WebView2_INCLUDE_DIRS ${WebView2_include_dir})
    set(WebView2_LIBRARIES ${WebView2_library})
    mark_as_advanced(WebView2_library WebView2_include_dir WebView2_root_dir)

    if(NOT TARGET juce_webview2)
        add_library(juce_webview2 INTERFACE)
        add_library(juce::juce_webview2 ALIAS juce_webview2)
        target_include_directories(juce_webview2 INTERFACE ${WebView2_INCLUDE_DIRS})
        target_link_libraries(juce_webview2 INTERFACE ${WebView2_LIBRARIES})
    endif()
elseif(NOT WebView2_FIND_QUIETLY)
    message(WARNING
            "WebView2 wasn't found. Checked: PackageManagement, .nuget/packages, _tools/packages.\n"
            "Install via: nuget install Microsoft.Web.WebView2 -Version 1.0.3485.44 -OutputDirectory _tools/packages\n"
            "Or run: scripts/setup.ps1")
endif()
